version: 2
updates:
  - package-ecosystem: npm
    directory: "/backend"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
