/** Extensões de liquidez — fundidas em `sector-universe.ts` (dedupe + cap `getSectorBookMaxTickers`). */

const w = (s: string) => s.trim().split(/\s+/).filter(Boolean);

export const XL_BR_COMMODITIES = w(`
ASAI3 MULT3 DIRR3 CYRE3 EZTC3 MRVE3 JHSF3 HBSA3 CAMB3 VULC3 WHRL4 LAND3 AGXY3 CBAV3
RAIZ4 SLCE3 SOJA3 AGRO3 TTEN3 MILS3 CEAB3 JALL3 TGMA3 KLAS3 MDIA3 NEMO6 SONO6 MSPA3
PTBL3 MTSA4 DOHL4 RSUL4 TASA4 CURY3 ORVR3 NINJ3 VITT3`);

export const XL_BR_TECHNOLOGY = w(`
B3SA3 SQIA3 WIZC3 DOTZ3 DESK3 TESA3 INTB3 PRNR3 VAMO3 PART3 FIQL3 NINJ3 IGTI11
NVDC34 GOGL34 META34 NFLX34 DIS34 ORCL34 ADBE34 CRM34 INTC34 AMD34 AVGO34 QCOM34 TXN34
IBM34 CSCO34 HPQ34 DELL34 PANW34 SHOP34 COIN34 UBER34 ABNB34 BKNG34 PYPL34`);

export const XL_BR_OIL_GAS = w(`
RECV3 UGPA3 OSX3 RPMG3 ENMT3 EQTL3 CSAN3
XOM34 CVX35 COP34 SLB34 OXY34 EOG34 HAL34 BKR34 WMB34 KMI34 PSX34 VLO34 MPC34 APA34
CHK34 DVN34 MRO34 OKE34 TRGP34 FANG34 CTRA34 IMO34 SU34 CNQ34 BP34 SHEL34 TTE34 ENB34`);

export const XL_BR_DEFENSE_AEROSPACE = w(`
EMBR3 LMT34 RTX34 NOC34 GD34 BA34 TXT34 SPR34 CW34 GE34 CAT34 TDY34 HEI34 HWM34 LDOS34
HII34 LHX34 TXT34 KTOS34`);

export const XL_BR_FINANCIALS = w(`
BPAN4 BARI11 ITUB3 BBDC3 SULA11 PSSA3 IRBR3 CXSE3 BRPR3 BRAP4 BAZA4 BMIN3 BMGB4 ABCB4
BRSR6 BANB3 BMOB3 TRIS3 ENBR3`);

export const XL_BR_HEALTHCARE = w(`
RADL3 HAPV3 RDOR3 ONCO3 QUAL3 FLRY3 MDIA3 DASA3 PARD3 PNVL3 HYPE3 ODPV3 NRTQ3
PFIZ34 JNJ34 UNH34 ABT34 MDT34 SYK34 BSX34`);

export const XL_BR_CONSUMER = w(`
SOMA3 ARZZ3 BHIA3 CRFB3 AMER3 SEQL3 PASS3 PETZ3 NATU3 GRND3 WHRL4 VULC3 ALPA4 CAML3`);

export const XL_BR_UTILITIES = w(`
NEOE3 EGIE3 ENEV3 AESB3 CPLE11 CPFE11 SAPR TAEE`);

export const XL_BR_INDUSTRIALS = w(`
ROMI3 VLID3 AGXY3 SHOW3 STBP3 AZUL4 GOLL4 RAIL3 TUPY3 KEPL11 FRAS RAPT`);

/* Corrige aliases sem sufixo (typos herdados) onde ainda válidos na B3 */
function normBr(xs: readonly string[]): string[] {
  const map: Record<string, string> = {
    TAEE: "TAEE11",
    SAPR: "SAPR11",
    FRAS: "FRAS3",
    RAPT: "RAPT4",
  };
  return xs.map((s) => map[s] ?? s);
}

export const XL_BR_COMMODITIES_N = normBr(XL_BR_COMMODITIES);
export const XL_BR_TECHNOLOGY_N = normBr(XL_BR_TECHNOLOGY);
export const XL_BR_OIL_GAS_N = normBr(XL_BR_OIL_GAS);
export const XL_BR_DEFENSE_AEROSPACE_N = normBr(XL_BR_DEFENSE_AEROSPACE);
export const XL_BR_FINANCIALS_N = normBr(XL_BR_FINANCIALS);
export const XL_BR_HEALTHCARE_N = normBr(XL_BR_HEALTHCARE);
export const XL_BR_CONSUMER_N = normBr(XL_BR_CONSUMER);
export const XL_BR_UTILITIES_N = normBr(XL_BR_UTILITIES);
export const XL_BR_INDUSTRIALS_N = normBr(XL_BR_INDUSTRIALS);

export const XL_INTL_COMMODITIES = w(`
STLD CLF MP ALB SQM TECK MT SCCO AA PKG IP NTR CTVA MOS FMC ADM BG CF RIO BHP VALE
LEU CCJ UEC`);

export const XL_INTL_TECHNOLOGY = w(`
ASML SNAP PLTR SNOW NET CRWD TEAM ZS DDOG OKTA ANET SPLK VEEV RNG INTU PAYC HUBS ADSK
WDAY FSLR ENPH TER ROK STX ZM DOCU PATH SOFI COIN SHOP SPOT TWLO RDDT APP MDB
ESTC GTLB IOT SNPS CDNS ANSS FTNT SMCI HPE PANW`);

export const XL_INTL_OIL_GAS = w(`
OVV WFRD NOV CHK AR RRC SWN PR SM EOG DVN HES COP CVX XOM SLB MPC VLO PSX OXY HAL BKR
KMI WMB ET OKE TRGP FANG CTRA APA MRO MTDR MGY CNQ SU IMO BP SHEL TTE ENB TRP CVE`);

export const XL_INTL_DEFENSE = w(`
GE HON MMM CAT DE EMR ETN ROK ITT AXON OSK WWD HEI LHX NOC GD BA LMT RTX TXT HII TDG
SPR CW LDOS CACI SAIC KTOS AVAV RKLB JOBY ACHR`);

export const XL_INTL_FINANCIALS = w(`
SCHW COIN HOOD ARES TROW IVZ NTRS STT BK SPGI MCO MSCI KKR BX APO OWL RJF LPLA FUTU
IBKR RDN WRB HIG CNA LNC RNR MKL BRO PFG AFL MET PRU ALL TRV CB PGR AIG UNM CINF`);

export const XL_INTL_HEALTHCARE = w(`
VEEV IQV HOLX RMD CAH MCK ELV CNC MOH IDXX WST STE VTRS ZBH HOLX EXAS NBIX BMRN INCY
REGN VRTX ILMN DXCM ISRG SYK BSX EW MDT ZBH HCA PFE DHR JNJ UNH LLY ABBV MRK TMO BMY
AMGN GILD CVS CI HUM MRNA BIIB`);

export const XL_INTL_CONSUMER = w(`
FIVE DKS LULU DECK SKX CROX WING CMG DPZ YUM MCD SBUX NKE TGT HD LOW COST WMT EL ULTA
CHD CLX KMB PG KO PEP MDLZ MNST KDP SJM CPB HSY KHC GIS CL STZ TAP SAM BFB`);

export const XL_INTL_UTILITIES = w(`
DUK SO NEE AEP D XEL WEC CMS DTE EIX PCG FE ETR ES AWK LNT NI AEE EVRG PNW CNP EXC PPL
ATO OGE IDA OGS SR NWE ALE HE NJR OTTR SJW MGEE WTRG CWT CWEN BEPC ORA`);

export const XL_INTL_INDUSTRIALS = w(`
EMR ETN ROK TT IR PH ITW FAST DOV XYL AME GNRC PNR FTV CMI PCAR WWD ATKR MTZ PWR J VMC
MLM JBHT CHRW EXPD SNDR SAIA ODFL KNX CSX NSC UNP CP WAB`);
