export const SECURITY_EVENT_TYPES = [
  'LOGIN_SUCCESS',
  'LOGIN_FAILED',
  'LOGIN_NEW_DEVICE',
  'LOGOUT',
  'LOGOUT_ALL',
  'REFRESH_REUSE',
  'REFRESH_BIND_MISMATCH',
  'PASSWORD_RESET',
  'SESSION_REVOKED',
  'SESSION_REVOKED_ALL',
  'WEBAUTHN_REGISTERED',
  'WEBAUTHN_REMOVED',
  'WEBAUTHN_LOGIN_SUCCESS',
  'ACCOUNT_LOCKOUT',
  'INTERNAL_API_PROBE_FAILED',
  'PASSWORD_BREACH_BLOCKED',
  'ADMIN_IP_DENIED',
] as const;

export type SecurityEventType = (typeof SECURITY_EVENT_TYPES)[number];
